'use strict';
const assert=require('node:assert/strict');const {test}=require('node:test');
const {relativeLink,linkRequest,resolveRequest,renderLink,bind}=require('../frontend/document-links.js');
const note='a'.repeat(32),item='b'.repeat(32),target='../%E4%B8%AD%E6%96%87%20file.docx#yx-item='+item;
test('standard encoded relative paths and stable fragments remain portable',()=>{for(const value of [target,'../file.docx','other%23hash.txt','file%25name.txt'])assert.equal(relativeLink(value),true,value);assert.equal(new URLSearchParams(linkRequest(note,item).split('?')[1]).get('item'),item);assert.equal(new URLSearchParams(resolveRequest(note,target).split('?')[1]).get('path'),target);});
test('unsupported schemes, absolute paths, queries and malformed fragments stay inert',()=>{for(const value of ['https://evil/x','//host/a','/root','file:///x','a?x=1','foo#heading','a#yx-item=bad','%2fetc','%5cserver','a%00.txt','%GG','a b']){assert.equal(relativeLink(value),false,value);assert.doesNotMatch(renderLink('safe',value,note),/<a/);}});
test('rendered local anchors escape all untrusted labels and attributes',()=>{const html=renderLink('<img onerror="x">',target,note);assert.match(html,/data-yx-document-link=/);assert.match(html,/href="#yx-file"/);assert.doesNotMatch(html,/<img/);assert.match(html,/&lt;img/);assert.equal(renderLink('outside',target,'external-id'),'outside');});
test('file link requests require registered project identifiers',()=>{for(const id of ['',null,'../x','A'.repeat(32)])assert.throws(()=>linkRequest(id,item));assert.throws(()=>resolveRequest(note,'https://evil'));});
function fixture(api){const listeners={},opened=[],errors=[];const root={addEventListener:(k,v)=>listeners[k]=v,removeEventListener:k=>delete listeners[k],contains:()=>true};const control=bind({root,api,onOpen:(...v)=>opened.push(v),onError:e=>errors.push(e.message)});const event=()=>({target:{closest:()=>({dataset:{yxNote:note,yxDocumentLink:target}})},preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;}});return {listeners,opened,errors,control,event};}
test('a click resolves against backend before opening an item',async()=>{const calls=[];const s=fixture(async url=>{calls.push(url);return {id:item,name:'doc'};});const e=s.event();await s.listeners.click(e);assert.equal(e.prevented,true);assert.equal(e.stopped,true);assert.equal(s.opened[0][0],item);assert.equal(calls[0],resolveRequest(note,target));s.control.destroy();assert.equal(s.listeners.click,undefined);});
test('failed authorization opens nothing and reports the error',async()=>{const s=fixture(async()=>{throw Error('不同项目');});await s.listeners.click(s.event());assert.deepEqual(s.opened,[]);assert.deepEqual(s.errors,['不同项目']);});
test('duplicate pending clicks and destroyed views cannot open stale targets',async()=>{let release;const s=fixture(()=>new Promise(r=>release=r));const pending=s.listeners.click(s.event());await s.listeners.click(s.event());s.control.destroy();release({id:item});await pending;assert.deepEqual(s.opened,[]);});
test('host receives the authorized anchor so it can check the active document',async()=>{const s=fixture(async()=>({id:item}));const event=s.event(),anchor=event.target.closest();event.target.closest=()=>anchor;await s.listeners.click(event);assert.equal(s.opened[0][2],anchor);});
test('a detached root cannot open its still-contained anchor after resolution',async()=>{let release;const s=fixture(()=>new Promise(r=>release=r));const event=s.event(),anchor=event.target.closest();anchor.isConnected=true;event.target.closest=()=>anchor;const pending=s.listeners.click(event);anchor.isConnected=false;release({id:item});await pending;assert.deepEqual(s.opened,[]);});
