'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {test}=require('node:test');
function setup() {
  const calls=[],messages=[],dialogs=[],nodes=new Map();
  const context=vm.createContext({setTimeout,localStorage:{getItem:()=>null,setItem:()=>{}},window:{chrome:{webview:{postMessage:value=>messages.push(value)}}},document:{querySelector:key=>{if(!nodes.has(key))nodes.set(key,{open:false,value:'',innerHTML:''});return nodes.get(key);}},
    FormData:class {constructor(form){this.values=form;}has(key){return !!this.values[key];}get(key){return this.values[key];}},
    fakeApi:async(url,options)=>{calls.push({url,options});return url==='/api/settings' ? (options?.body || {confirm_delete:true,confirm_trash_delete:true,close_to_tray:true,autoplay_media:false,default_view:'grid',default_sort:'updated'}) : {id:'a'.repeat(32),name:'<unsafe>.txt',kind:'text',path:'C:/fixture.txt',content:{editable:true,content:'read only'}};},
    fakeDialog:options=>dialogs.push(options)});
  const source=fs.readFileSync(path.join(__dirname,'../frontend/app.js'),'utf8').replace(/boot\(\);\s*$/,'');
  vm.runInContext(source+`\napi=fakeApi;showDialog=fakeDialog;toast=()=>{};report=()=>{};renderWorkspace=()=>{};renderTabs=()=>{};configureSection=()=>{};loadItems=async()=>{};guardProperties=async()=>true;choose=async()=>{globalThis.asked=true;return 'cancel';};prepareTabs=async()=>true;persistDrafts=()=>{};globalThis.app={state,preference,confirmRemoval,settingsDialog,openExternal,handleDesktopMessage};`,context);
  context.app.state.bootstrap={settings:{}};return {...context.app,context,calls,messages,dialogs,nodes};
}
test('normal delete confirms by default and honors an explicit opt-out',async()=>{const s=setup();assert.equal(await s.confirmRemoval('x','y',[]),'cancel');assert.equal(s.context.asked,true);s.context.asked=false;s.state.bootstrap.settings.confirm_delete=false;assert.equal(await s.confirmRemoval('x','y',[]),'delete');assert.equal(s.context.asked,false);});
test('saving settings persists all switches and notifies the desktop only after success',async()=>{const s=setup();await s.settingsDialog();assert.match(s.dialogs[0].body,/清理回收站前确认/);await s.dialogs[0].onSubmit({confirm_delete:true,close_to_tray:true,default_view:'list',default_sort:'name'});const saved=s.calls[1];assert.equal(saved.options.method,'PATCH');assert.equal(saved.options.body.confirm_trash_delete,false);assert.equal(s.state.view,'list');assert.equal(s.state.sort,'name');assert.equal(s.messages[0].action,'settings-changed');});
test('settings cannot replace an existing confirmation dialog',async()=>{const s=setup();s.nodes.set('#appDialog',{open:true});await s.settingsDialog();assert.equal(s.calls.length,0);assert.equal(s.dialogs.length,0);});
test('external documents open in a separate read-only preview without creating project records',async()=>{const s=setup();await s.openExternal('a'.repeat(32));assert.equal(s.state.tabs[0].source,'external');assert.equal(s.state.tabs[0].mode,'preview');assert.equal(s.state.tabs[0].content.editable,false);assert.equal(s.state.tabs[0].dirty,false);assert.equal(s.calls.length,1);assert.equal(s.calls[0].url,'/api/external/'+'a'.repeat(32));await s.openExternal('a'.repeat(32));assert.equal(s.state.tabs.length,1);});
test('invalid external ids never turn into a path read',async()=>{const s=setup();await assert.rejects(s.openExternal('../secret'));assert.equal(s.calls.length,0);});
test('exit handshake rejects exit during a confirmation and permits it after draft preparation',async()=>{const s=setup();s.nodes.set('#appDialog',{open:true});await s.handleDesktopMessage({action:'prepare-exit',requestId:'one'});assert.equal(s.messages[0].allow,false);s.nodes.get('#appDialog').open=false;await s.handleDesktopMessage({action:'prepare-exit',requestId:'two'});assert.equal(s.messages[1].allow,true);assert.equal(s.messages[1].requestId,'two');});
test('concurrent external-open messages queue behind the current modal without replacing its confirmation',async()=>{const s=setup();s.nodes.set('#appDialog',{open:true});const one=s.handleDesktopMessage({action:'external-open',entries:[{id:'a'.repeat(32)}]});const two=s.handleDesktopMessage({action:'external-open',entries:[{id:'b'.repeat(32)}]});assert.equal(s.calls.length,0);assert.equal(s.state.externalQueue.length,2);s.nodes.get('#appDialog').open=false;await Promise.all([one,two]);assert.equal(s.state.tabs.length,2);assert.deepEqual(s.calls.map(c=>c.url),['/api/external/'+'a'.repeat(32),'/api/external/'+'b'.repeat(32)]);});
test('dirty-property confirmation for one external file completes before the next request starts',async()=>{const s=setup();vm.runInContext(`globalThis.releaseGuard=null;globalThis.guardCalls=0;guardProperties=async()=>{guardCalls++;if(guardCalls===1)await new Promise(resolve=>releaseGuard=resolve);return true;};`,s.context);const one=s.handleDesktopMessage({action:'external-open',entries:[{id:'a'.repeat(32)}]});const two=s.handleDesktopMessage({action:'external-open',entries:[{id:'b'.repeat(32)}]});assert.equal(s.context.guardCalls,1);s.context.releaseGuard();await Promise.all([one,two]);assert.equal(s.context.guardCalls,2);assert.equal(s.state.tabs.length,2);});
test('sidebar contains at most five unique current/recent live projects',()=>{const s=setup();s.state.projects=Array.from({length:20},(_,i)=>({id:String(i)}));s.state.projectId='10';s.state.projectLibrary={recent_ids:['missing','10','2','2','3','4','5','6']};const ids=vm.runInContext('sidebarProjects().map(p=>p.id)',s.context);assert.deepEqual(Array.from(ids),['10','2','3','4','5']);});
