'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),Module=require('node:module');
const {test}=require('node:test'),{execFile}=require('node:child_process'),{promisify}=require('node:util'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),dependencies=path.join(root,'tools/markdown-editor/node_modules');
if(!fs.existsSync(path.join(dependencies,'esbuild')))test('link source checks need existing offline build dependencies',{skip:true},()=>{});
else{
 const esbuild=require(path.join(dependencies,'esbuild')),source=fs.readFileSync(path.join(root,'frontend/live-markdown-source.mjs'),'utf8');
 const built=esbuild.buildSync({stdin:{contents:source+'\nexport {buildEditorState,previewDecorations,DocumentLinkWidget};',resolveDir:path.join(root,'frontend'),loader:'js'},nodePaths:[dependencies],bundle:true,write:false,platform:'node',format:'cjs'});
 const loaded=new Module(path.join(root,'link-check.cjs'),module);loaded.filename=path.join(root,'link-check.cjs');loaded._compile(built.outputFiles[0].text,loaded.filename);const api=loaded.exports;
 function state(text,onLink=()=>{},mode='live'){let s=api.buildEditorState(text,mode,'测试',null,null,onLink).state;return s.update({selection:{anchor:s.doc.length}}).state;}
 function links(s,focus=true){const list=[];api.previewDecorations(s,undefined,focus).between(0,s.doc.length,(_f,_t,dec)=>{if(dec.spec.widget instanceof api.DocumentLinkWidget)list.push(dec.spec.widget);});return list;}
 test('escaped brackets in standard Markdown labels produce readable local links',()=>{const text='[文件\\[1\\]](../files/a.docx#yx-item='+('a'.repeat(32))+')\n\n末尾',s=state(text),found=links(s);assert.equal(found.length,1);assert.equal(found[0].label,'文件[1]');assert.equal(found[0].local,true);assert.equal(s.sliceDoc(),text);});
 test('HTTP links have explicit browser semantics and local links require a host callback',()=>{const s=state('[外链](https://example.invalid/a)\n\n[本地](../a.docx)\n\n末尾',null),found=links(s);assert.equal(found.length,1);assert.equal(found[0].url,'https://example.invalid/a');assert.equal(found[0].local,false);});
 test('cursor anywhere on the link line exposes source without changing it',()=>{const raw='前文 [文件](../a.docx) 后文\n\n末尾',s=state(raw);assert.equal(links(s).length,1);assert.equal(links(s.update({selection:{anchor:0}}).state).length,0);assert.equal(links(state(raw,()=>{},'source')).length,0);assert.equal(s.sliceDoc(),raw);});
 test('dangerous and encoded schemes never become clickable widgets',()=>{for(const url of ['javascript:alert','data:text/html,x','file:///C:/a','//evil/x','/private','%6Aavascript%3Aalert','%2F%2Fevil/x','../a%00.txt','../a%5Cb.txt','../a#yx-item=bad'])assert.equal(links(state('[链接]('+url+')\n\n末尾')).length,0,url);});
 test('angle-bracket paths with spaces are passed to the host as encoded relative URLs',()=>{const found=links(state('[文件](<../本地 文件.docx>)\n\n末尾'));assert.equal(found.length,1);assert.equal(found[0].url,'../本地%20文件.docx');});
}
test('real Chromium live links open callbacks, preserve source and obey composition',async t=>{
 const browser=[process.env.YINGXU_TEST_BROWSER,'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(p=>p&&fs.existsSync(p));if(!browser){t.skip('Existing Chromium required');return;}
 const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'yingxu-md-links-'));t.after(()=>{const resolved=path.resolve(temporary);assert.ok(resolved.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(resolved).startsWith('yingxu-md-links-'));fs.rmSync(resolved,{recursive:true,force:true,maxRetries:10,retryDelay:100});});
 fs.copyFileSync(path.join(root,'frontend/live-markdown.js'),path.join(temporary,'editor.js'));
 fs.writeFileSync(path.join(temporary,'runner.js'),`(async()=>{
 const result=[],check=(name,ok)=>result.push({name,ok}),tick=()=>new Promise(r=>setTimeout(r,80));let changes=0;const opened=[];
 const raw='[文件\\\\[1\\\\]](../a.docx#yx-item='+'a'.repeat(32)+')\\n\\n[网站](https://example.invalid)\\n\\n末尾'.replace(/\\\\n/g,'\\n');
 const editor=YingXuMarkdown.create({parent:document.querySelector('#editor'),value:raw,onLink:url=>opened.push(url),onChange:()=>changes++});editor.revealMatch({from:raw.length,to:raw.length,focus:true});await tick();
 let anchors=document.querySelectorAll('.yx-md-document-link');check('live link label unescapes brackets',anchors.length===2&&anchors[0].textContent==='文件[1]');const before=editor.getSelection();anchors[0].click();await tick();check('local callback receives the original encoded path',opened.length===1&&opened[0].includes('#yx-item='));check('click never modifies draft or cursor',editor.getValue()===raw&&changes===0&&JSON.stringify(editor.getSelection())===JSON.stringify(before));check('HTTP target is isolated',anchors[1].getAttribute('target')==='_blank'&&anchors[1].rel.includes('noopener'));
 const content=document.querySelector('.cm-content');content.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));anchors[0].click();check('composition blocks link activation',opened.length===1);content.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));await tick();
 editor.revealMatch({from:0,to:0,focus:true});await tick();check('active link line shows source for editing',document.querySelectorAll('.yx-md-document-link').length===1);editor.setMode('source');await tick();check('source mode keeps literal links with no clickable widgets',!document.querySelector('.yx-md-document-link')&&editor.getValue()===raw);editor.destroy();check('destroy leaves no editor DOM',!document.querySelector('.cm-editor'));document.querySelector('#result').textContent=JSON.stringify(result);
 })().catch(error=>document.querySelector('#result').textContent=JSON.stringify({error:String(error),stack:error.stack}));`);
 fs.writeFileSync(path.join(temporary,'fixture.html'),'<!doctype html><meta charset="utf-8"><div id="editor"></div><pre id="result"></pre><script src="editor.js"></script><script src="runner.js"></script>');
 const {stdout}=await promisify(execFile)(browser,['--headless','--disable-gpu','--no-first-run','--disable-background-networking',`--user-data-dir=${path.join(temporary,'profile')}`,'--virtual-time-budget=4000','--dump-dom',pathToFileURL(path.join(temporary,'fixture.html')).href],{windowsHide:true,timeout:30000,maxBuffer:2*1024*1024});
 const match=stdout.match(/<pre id="result">([^<]+)<\/pre>/);assert.ok(match,stdout.slice(-1500));const result=JSON.parse(match[1].replace(/&quot;/g,'"').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>'));assert.ok(Array.isArray(result),JSON.stringify(result));assert.equal(result.length,8);for(const row of result)assert.equal(row.ok,true,row.name);
});
