'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {test}=require('node:test'),{execFile}=require('node:child_process'),{promisify}=require('node:util'),{pathToFileURL}=require('node:url');
test('real app DOM inserts project links from drops and guards asynchronous document changes',async t=>{
 const browser=[process.env.YINGXU_TEST_BROWSER,'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(p=>p&&fs.existsSync(p));if(!browser){t.skip('Existing Chromium required');return;}
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'yingxu-doc-links-app-'));t.after(()=>{const root=path.resolve(tmp);assert.ok(root.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(root).startsWith('yingxu-doc-links-app-'));fs.rmSync(root,{recursive:true,force:true,maxRetries:10,retryDelay:100});});
 const front=path.join(__dirname,'../frontend');for(const file of ['document-links.js','live-markdown.js','live-markdown.css','styles.css'])fs.copyFileSync(path.join(front,file),path.join(tmp,file));
 fs.writeFileSync(path.join(tmp,'app.js'),fs.readFileSync(path.join(front,'app.js'),'utf8').replace(/boot\(\);\s*$/,''));
 fs.writeFileSync(path.join(tmp,'runner.js'),String.raw`(async()=>{
 const checks=[],check=(name,ok)=>checks.push({name,ok}),tick=()=>new Promise(r=>setTimeout(r,160)),errors=[],calls=[],uploads=[],opened=[],notices=[];let hold=null,pending=null;
 report=error=>errors.push(String(error));renderInspector=()=>{};persistDrafts=()=>{};guardProperties=async()=>true;toast=(...args)=>notices.push(args);
 const p='a'.repeat(32),note='b'.repeat(32),other='c'.repeat(32),item='d'.repeat(32),uploaded='e'.repeat(32);
 const link=id=>'[文件'+String.fromCharCode(92)+'[1'+String.fromCharCode(92)+']](../references/%E6%96%87%E4%BB%B6%5B1%5D.docx#yx-item='+id+')';
 api=async url=>{calls.push(url);if(hold){const expected=hold;hold=null;await new Promise(resolve=>pending=resolve);check('awaited request reached '+expected,url.includes(expected));}return url.includes('file-link?')?{markdown:link(new URL(url,'https://local').searchParams.get('item'))}:{id:item,project_id:p,name:'文件[1]',kind:'docx'};};
 uploadFiles=async(files,category,folder,project)=>{uploads.push({files,category,folder,project});return[{id:uploaded}];};openItem=async id=>opened.push(id);
 const make=(id,name)=>({key:'file:'+id,id,source:'file',mode:'edit',dirty:false,draft:'开头\r\n正文',item:{id,project_id:p,kind:'markdown',name,metadata:{}},content:{editable:true,content:'开头\r\n正文'}});
 const markdownModule=window.YingXuMarkdown;window.YingXuMarkdown=undefined;
 const md=make(note,'笔记'),second=make(other,'另一笔记');Object.assign(state,{projects:[{id:p,name:'项目'}],projectId:p,bootstrap:{settings:{},capabilities:{}},tabs:[md,second],activeKey:md.key});wireEvents();renderWorkspace();
 const card=document.createElement('div');card.dataset.item=item;card.draggable=true;$('#resourceViewport').append(card);
 const drop=(ids,files=[])=>{const transfer=new DataTransfer();if(ids.length){card.dispatchEvent(new DragEvent('dragstart',{dataTransfer:transfer,bubbles:true,cancelable:true}));}for(const file of files)transfer.items.add(file);$('#editorContent').dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,bubbles:true,cancelable:true}));};
 $('#textEditor').setSelectionRange(2,2);const before=md.draft;drop([item]);await tick();check('registered card drop inserts standard link without upload or move',md.draft.includes(link(item))&&md.draft.startsWith('开头\r\n')&&uploads.length===0&&calls.length===1&&calls[0].includes('file-link?'));
 check('drop only changes draft and preserves existing body',md.dirty&&md.draft.endsWith('\r\n正文')&&md.content.content===before);
 md.mode='preview';renderWorkspace();await tick();const anchor=document.querySelector('[data-yx-document-link]');check('preview displays escaped bracket label as one safe anchor',anchor?.textContent==='文件[1]'&&anchor.getAttribute('href')==='#yx-file');anchor?.click();await tick();check('preview click resolves registered item before opening',opened.length===1&&opened[0]===item&&calls.at(-1).includes('resolve-file?'));
 md.mode='edit';renderWorkspace();hold='file-link?';const previous=md.draft;drop([item]);await tick();state.activeKey=second.key;renderWorkspace();pending();await tick();check('late link after tab switch inserts in neither draft',md.draft===previous&&second.draft==='开头\r\n正文'&&!documentLinkBusy);
 state.activeKey=md.key;renderWorkspace();hold='file-link?';drop([item]);await tick();$('#textEditor').value+='新编辑';$('#textEditor').dispatchEvent(new Event('input',{bubbles:true}));const changed=md.draft;pending();await tick();check('late link after typing does not overwrite new draft',md.draft===changed&&!documentLinkBusy);
 hold='file-link?';drop([item]);await tick();$('#textEditor').dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));const imeDraft=md.draft;pending();await tick();check('pending link does not insert during textarea composition',md.textComposing&&md.draft===imeDraft&&!documentLinkBusy);$('#textEditor').dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));
 hold='file-link?';drop([item]);await tick();md.content.editable=false;pending();await tick();check('pending link respects changed editing permission',md.draft===imeDraft&&!documentLinkBusy);md.content.editable=true;
 const file=new File(['synthetic Word fixture'], '外部.docx',{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});drop([],[file]);await tick();check('Explorer Word delegates copy to current project references before linking returned ID',uploads.length===1&&uploads[0].category==='references'&&uploads[0].folder===null&&uploads[0].project===p&&uploads[0].files[0].name==='外部.docx'&&md.draft.includes(link(uploaded)));
 const count=calls.length,raw=md.draft;md.source='external';drop([item]);await tick();check('external Markdown is explicitly rejected without API or edits',calls.length===count&&md.draft===raw&&notices.at(-1)[0].includes('当前项目'));md.source='file';
 window.YingXuMarkdown=markdownModule;md.mode='live';md.draft='光标行\n\n'+link(item)+'\n';renderWorkspace();await tick();const live=document.querySelector('.yx-md-document-link');check('live Markdown renders escaped label without rewriting source',live?.textContent==='文件[1]'&&md.markdownEditor.getValue()===md.draft);live?.click();await tick();check('live link click invokes authorized resolver and open',opened.length===2&&opened.at(-1)===item);
 hold='resolve-file?';document.querySelector('.yx-md-document-link')?.click();await tick();state.activeKey=second.key;renderWorkspace();const oldOpens=opened.length;pending();await tick();check('late live link resolution does not reopen target after switching documents',opened.length===oldOpens);
 check('no integration exceptions',errors.length===0);$('#auditResult').textContent=JSON.stringify(checks);
 })().catch(error=>document.querySelector('#auditResult').textContent=JSON.stringify({error:String(error),stack:error.stack}));`);
 let html=fs.readFileSync(path.join(front,'index.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,'');
 html=html.replace('</head>','<link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="live-markdown.css"></head>').replace('</body>','<pre id="auditResult"></pre><script src="document-links.js"></script><script src="live-markdown.js"></script><script src="app.js"></script><script src="runner.js"></script></body>');fs.writeFileSync(path.join(tmp,'fixture.html'),html);
 const {stdout}=await promisify(execFile)(browser,['--headless','--disable-gpu','--no-first-run','--disable-background-networking',`--user-data-dir=${path.join(tmp,'profile')}`,'--virtual-time-budget=10000','--dump-dom',pathToFileURL(path.join(tmp,'fixture.html')).href],{windowsHide:true,timeout:30000,maxBuffer:3*1024*1024});
 const match=stdout.match(/<pre id="auditResult">([^<]+)<\/pre>/);assert.ok(match,stdout.slice(-1800));const result=JSON.parse(match[1].replace(/&quot;/g,'"').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>'));assert.ok(Array.isArray(result),JSON.stringify(result));assert.equal(result.length,19);for(const row of result)assert.equal(row.ok,true,row.name);
});

